### ISSUE TITLE
UCP issue

### ISSUE THREAD

**Issue by spitefultowel** [bbDKP/bbGuild#265]
Attempting to load the bbGuild page on UCP (https://guild.com/ucp.php?i=210) and get the following error.

2016/02/24 20:44:39 [error] 19741#0: *1271 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template ".html" (looked into: ./ext/bbdkp/bbguild/styles/prosilver/template, ./ext/bbdkp/bbguild/styles/prosilver/theme, ./styles/prosilver/template, ./styles/prosilver/theme).' in /usr/share/nginx/guild/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:195
Stack trace:
#0 /usr/share/nginx/guild/phpbb/template/twig/loader.php(107): Twig_Loader_Filesystem->findTemplate('.html')
#1 /usr/share/nginx/guild/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(138): phpbb\template\twig\loader->findTemplate('.html')
#2 /usr/share/nginx/guild/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Filesystem->getCacheKey('.html')
#3 /usr/share/nginx/guild/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('.html', NULL)
#4 /usr/share/nginx/guild/phpbb/template/twig/environment.php(151): Twig_Enviro" while reading response header from upstream, client: <CLIENTIP>, server: guild.com, request: "GET /ucp.php?i=210 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "guild.com", referrer: "https://guild.com/ucp.php"

Fresh install of phpBB 3.1 with a tarball of bbGuild from git.

**Comment by Sajaki** [comment]
ucp isn't implemented yet.

**Comment by spitefultowel** [comment]
Ah okay.
