### ISSUE TITLE
No route for GET /

### ISSUE THREAD

**Issue by spitefultowel** [bbDKP/bbGuild#268]
`No route found for "GET /"` when loading the index.

**Comment by Uggers** [comment]
Ditto, not sure what this is tried checking everything was good style wise

**Comment by Sajaki** [comment]
it depends. 
http://localhost:8082/qi31/boards/demo01/app.php/ 
-> No route found for "GET /"
this is normal
-> http://localhost:8082/qi31/boards/demo01/app.php/guild/roster
roster page loads.
-> http://localhost:8082/qi31/boards/demo01/app.php/guild
errror page (because welcome page isn't done.

**Comment by Sajaki** [comment]
it should not happen again in build A4.
CLOSING

**Comment by Uggers** [comment]
thanks for the fix,

quick question though, which is actually the main page then with the portal/recruitment block etc on.

I've got it all set up and with bbdkp it used to be /portal.php
My /app.php/guild is only showing a menu to the left with a drop down and a guild feed of loot drops

**Comment by Sajaki** [comment]
http://www.avathar.be/bbdkp/viewtopic.php?f=60&t=3538

**Comment by sgtevmckay** [comment]
(???)
I am registered at this site, but I am getting a No Authorization to view notice
