### ISSUE TITLE
2.0.0-a4 - adding a guild

### ISSUE THREAD

**Issue by scintin** [bbDKP/bbGuild#270]
Hi there :)

I'm watching your work and still hoping, that you'll finish it... <3

I just tried your current build. I could'nt add a guild cause of an unexpected '[' in line 408. So I changed the line. Just trying... ;)
It's guild_module.php (sorry, sometimes I'm a idiot)
        

>  $newrank->RankHide = $this->request->is_set_post('hide', $rank_id);

After uploading there's a new problem...I tried updating my guild automatically... ;)

> Fatal error: Call to undefined function bbdkp\bbguild\model\player\imagelayereffect() in /var/www/web853/html/forum/ext/bbdkp/bbguild/model/player/Guilds.php on line 583

Probably I'll try to repair it...but atm I'm a little bit tired ;)

Greetings

**Comment by Sajaki** [comment]
I couldn't reproduce your issues on my environment.
