### ISSUE TITLE
ACP - BBDKP not opening

### ISSUE THREAD

**Issue by Tankyspanky** [bbDKP/bbguild#275]
Just installed new version, no errors while installing.
But on ACP the BBDKP page wil not open got a 500 eror

De pagina op ***********.org werkt niet

*********.org kan dit verzoek momenteel niet verwerken.
500

**Comment by Sajaki** [comment]
please specify the php error. 
set "display_errors = on" in your php.ini

**Comment by Tankyspanky** [comment]
Seems i cannot turn that one, since its a rental domain server (hosted)
And i ment the "changed" alpha a6 as new :) 

Thanx anyway
