### ISSUE TITLE
Cannot Enable bbGuild

### ISSUE THREAD

**Issue by dgulliver** [bbDKP/bbguild#292]
Hi, 

I'm running phpbb 3.1.7 I ceated a directory within ext called bbdkp/bbguild but when I press the Enable I get a page that says information in a red bar but with no other detrails on why the extension didn't enable.

Cheers
Darren

**Comment by Sajaki** [comment]
should be fixed.

**Comment by dgulliver** [comment]
Thank you Sajaki,

I'm now seeing a message when I try to enable:

> information
> The selected extension cannot be enabled, please verify the extension’s requirements.

I checked php version which is 5.4.45

**Comment by Sajaki** [comment]
did you check the other requirements?
    phpbb > 3.1.3
    PHP >= 5.4.39
    PHP Client URL Library (php_curl.dll)
    PHP GD library (php_gd2.dll)

**Comment by dgulliver** [comment]
ok how do I check for:
PHP Client URL Library (php_curl.dll)
PHP GD library (php_gd2.dll)

as phpBB and php and greater than your minimum :)

**Comment by Sajaki** [comment]
easiest way is to open up the acp -> system tab -> php info, 
and then look for this : c

curl : used for calling the version number, blizzard battle.net to populate the roster, build the guild emblem...
![curl](https://cloud.githubusercontent.com/assets/226730/15684692/8354c75c-2768-11e6-8476-dc11cc46b5c2.png)

gd. this is a graphics library and it is used to draw pictures. 
![gd](https://cloud.githubusercontent.com/assets/226730/15684673/722b7bf6-2768-11e6-875d-99a88d27c116.png)
