### ISSUE TITLE
latest test version would not install

### ISSUE THREAD

**Issue by Tankyspanky** [bbDKP/bbguild#293]
Hello i have downloaded the latest version today Alpha2, and did a fresh install on my site.
I get a error when i tried to enable it:
> Information
> 
> The selected extension cannot be enabled, please verify the extension’s requirements.

I do believe i have all requirements:
GD Support	enabled
GD Version	bundled (2.1.0 compatible)
cURL support	enabled
cURL Information	7.19.7
PHP Version 5;6;9
And my Board is PHPBB 3;1;9

So i think i got it all ??

**Comment by bazgrim** [comment]
Yeah, I'm having the same issues. :(

**Comment by Sajaki** [comment]
i'm currently working on recent topics / pbwow. will pick this up after that.

**Comment by LeagueRaINi** [comment]
any information when it will be fixed ? 
or is there any other plugin like this for 3.1? rly need it :P :D

**Comment by Sajaki** [comment]
hi, i'm done with recent topic/pbwow now, they've been updated.  so i'll be picking up bbguild again.  but i'm working on a new style for Legion aswell ...

**Comment by Sajaki** [comment]
fixed
