### ISSUE TITLE
Error While Installing

### ISSUE THREAD

**Issue by LeagueRaINi** [bbDKP/bbguild#294]
**do i have to edit something or is it cause its alpha, i get so many errors even with older versions of bbguild**

**after deleting line 40 i can install it (cant install it with this line beein there)**
`$output .= $key . ' ' . (($val == true) ? ': OK' : ': KO') .=	'<br />' `

**Error while creating a Guild**
`Catchable fatal error: Argument 2 passed to bbdkp\bbguild\model\player\guilds::Call_Guild_API() must be an instance of bbdkp\bbguild\model\games\game, null given, called in /ext/bbdkp/bbguild/acp/guild_module.php on line 396 and defined in /ext/bbdkp/bbguild/model/player/guilds.php on line 761`

**Error trying to go to Personal Profil -> bbguild**
`Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template ".html" (looked into: ./ext/bbdkp/bbguild/styles/pbwow3/theme, ./ext/bbdkp/bbguild/styles/prosilver/template, ./ext/bbdkp/bbguild/styles/prosilver/theme, ./styles/pbwow3/template, ./styles/pbwow3/theme, ./styles/prosilver/template, ./styles/prosilver/theme).' in /vendor/twig/twig/lib/Twig/Loader/Filesystem.php:215 Stack trace: #0 /phpbb/template/twig/loader.php(107): Twig_Loader_Filesystem->findTemplate('.html') #1 /vendor/twig/twig/lib/Twig/Loader/Filesystem.php(139): phpbb\template\twig\loader->findTemplate('.html') #2 /vendor/twig/twig/lib/Twig/Environment.php(312): Twig_Loader_Filesystem->getCacheKey('.html') #3 /vendor/twig/twig/lib/Twig/Environment.php(378): Twig_Environment->getTemplateClass('.html', NULL) in /vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 215
`

**Comment by Sajaki** [comment]
hi, 
not sure why you're trying to circumvent the install checks.

**Comment by LeagueRaINi** [comment]
@Sajaki 
cause i cant intall it with line 40, i had to delete it.
guess i have to wait then ^^

**Comment by kaplanw** [comment]
phpbb version: 3.1.9
style: pbwow3
php version: 5.3.29
hosting company: mediatemple grid server

`Parse error: syntax error, unexpected T_CONCAT_EQUAL in /nfs/c01/h02/mnt/543/domains/heartofredemption.info/html/forums/ext/bbdkp/bbguild/ext.php on line 40`

I realize the php version is below the requirement... just adding in case it is helpful.
Thanks!

**Comment by orynider** [comment]
open common.php
Find:
if (!defined('IN_PHPBB'))
{
	exit;
}
Add After:
/* Define the tokens from the symbol table, just in case are not compiled in PHP5  */
if(!defined('T_CONCAT_EQUAL'))
{
	@define('T_CONCAT_EQUAL', 275);
	@define('T_STRING', 310);
	@define('T_OBJECT_OPERATOR', 363);
	@define('T_VARIABLE', 312);	
	@define('T_CONSTANT_ENCAPSED_STRING', 318);	
	@define('T_LNUMBER', 308);	
	@define('T_IF', 304);
	@define('T_ELSE', 306);
	@define('T_ELSEIF', 305);
	@define('T_WHITESPACE', 379);
	@define('T_FOR', 323);
	@define('T_FOREACH', 325);
	@define('T_WHILE', 321);
	@define('T_COMMENT', 374);
	@define('T_DOC_COMMENT', 375);				
}
/* Define the tokens from the symbol table, just in case are not compiled in PHP5  */
