### ISSUE TITLE
Issue updating Ranks from Armory

### ISSUE THREAD

**Issue by spitefultowel** [bbDKP/bbguild#297]
Please note that bbGuild is pre-Alpha software and is not intended for live installations. Use at your own risk.

please describe the steps to reproduce the problem.
Attempting to update the guild ranks from the Armory API

Expected behavior and actual behavior.
Expected is to download the ranks.

Actual

> General Error
> SQL ERROR [ mysqli ]
> 
> Incorrect integer value: '' for column 'faction' at row 1 [1366]
> 
> SQL
> 
> UPDATE phpbb_bb_guild SET achievementpoints = 0, level = 0, guildarmoryurl = '', emblemurl = '', battlegroup = '', armoryresult = 'OK', players = 0, faction = '' WHERE id= 1
> 
> BACKTRACE

Specifications
 - phpbb version : 3.2.0rc1
 - style : ProSilver
 - php version : 7.0
 - hosting company (optional)  :

**Comment by Sajaki** [comment]
hi, i couldn't reproduce this.
